// Config de Tailwind de la TIENDA (index.html). Tomada del tailwind.config inline de Stitch.
// El panel admin usa su propia paleta: ver tailwind.admin.config.js.
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

const sans = ['Plus Jakarta Sans', 'system-ui', 'sans-serif'];
const serif = ['Playfair Display', 'Georgia', 'serif'];

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/store/**/*.js', './src/shared/**/*.js'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#6e5e68',
        'inverse-primary': '#ffb1c3',
        surface: '#fcf8fa',
        'on-tertiary-container': '#4e3d00',
        'surface-dim': '#f2e4ea',
        'on-primary': '#ffffff',
        'surface-container': '#fdf2f8',
        'primary-fixed': '#ffd9e0',
        'surface-bright': '#ffffff',
        secondary: '#695a64',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#8f0042',
        'on-primary-fixed': '#3f0019',
        'surface-container-low': '#fff5f8',
        'secondary-fixed': '#f1dde9',
        outline: '#8d7075',
        'surface-tint': '#be185d',
        'on-secondary-fixed-variant': '#51434c',
        'tertiary-fixed': '#ffe088',
        'secondary-fixed-dim': '#d5c1cd',
        'on-secondary-fixed': '#231820',
        'on-tertiary': '#ffffff',
        'primary-fixed-dim': '#ffb1c3',
        'inverse-surface': '#27313f',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        primary: '#be185d',
        'primary-container': '#970046',
        'on-primary-container': '#ffd5dd',
        'surface-container-highest': '#fce7f3',
        'on-surface-variant': '#594046',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#fce7f3',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#574500',
        'tertiary-container': '#cba72f',
        background: '#fcf8fa',
        'inverse-on-surface': '#eaf1ff',
        'on-surface': '#1e1b1d',
        tertiary: '#735c00',
        'on-tertiary-fixed': '#241a00',
        'surface-container-high': '#f9d9e7',
        'secondary-container': '#efdae6',
        'outline-variant': '#f0ccd7',
        'on-background': '#1e1b1d',
        'tertiary-fixed-dim': '#e9c349',
        // Verde WhatsApp oscurecido para contraste AA con texto blanco (#25D366 da 2:1).
        whatsapp: { DEFAULT: '#15803d', hover: '#166534' },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '3rem',
        'space-lg': '1.75rem',
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        'space-sm': '0.5rem',
        gutter: '1.5rem',
        'space-xl': '3rem',
        'gutter-mobile': '1rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'label-sm': sans,
        'headline-xl': serif,
        'display-lg-mobile': serif,
        'label-lg': sans,
        'body-lg': sans,
        'headline-xl-mobile': serif,
        'title-md': sans,
        'editorial-italic': serif,
        'body-md': sans,
        'body-sm': sans,
        'headline-lg': serif,
        'headline-sm': serif,
        'display-lg': serif,
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0em', fontWeight: '600' }],
        'title-md': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'editorial-italic': ['20px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0em', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '600' }],
        'display-lg': ['54px', { lineHeight: '62px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
    },
  },
  plugins: [forms, containerQueries],
};
